<?php

declare(strict_types=1);

namespace Hibla\Mysql\Interfaces;

use Hibla\Sql\Result;

/**
 * Extends the core Result interface with MySQL-specific metadata.
 */
interface MysqlResult extends Result
{
    /**
     * Gets the number of warnings generated by the query execution.
     */
    public function getWarningCount(): int;
}
