<?php

declare(strict_types=1);

namespace Hibla\Mysql\Interfaces;

use Hibla\Mysql\ValueObjects\MysqlColumnDefinition;
use Hibla\Sql\Result;

/**
 * Extends the core Result interface with MySQL-specific metadata.
 */
interface MysqlResult extends Result
{
    /**
     * Gets the number of warnings generated by the query execution.
     */
    public function getWarningCount(): int;

    /**
     * Returns the full metadata for every column in the result set.
     *
     * @return array<int, MysqlColumnDefinition>
     */
    public function getFields(): array;

    /**
     * Get the connection id associated with the executed query.
     */
    public function getConnectionId(): int;

    /**
     * Returns the next result set if the query returned multiple result sets
     * (e.g. from a Stored Procedure or Multi-Statement query).
     *
     * @return self|null Returns the next result set, or null if no more exist.
     */
    public function nextResult(): ?self;
}
